EveryBook/Controllers/BugsController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Identity;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EveryBook.Data;
using EveryBook.Models;
using System.Collections;

namespace EveryBook.Controllers
{
    public class BugsController : Controller
    {
        private readonly EveryBookContext _context;
        private readonly UserManager<ExtendUser> _UserManager;

        public BugsController(EveryBookContext context, UserManager<ExtendUser> UserManager)
        {
            _context = context;
            _UserManager = UserManager;
        }

        // GET: Bugs
        public async Task<IActionResult> Index()
        {
            var everyBookContext = _context.Bug.Include(b => b.ExtendUser);
            return View(await everyBookContext.ToListAsync());
        }

        // GET: Bugs/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bug = await _context.Bug
                .Include(b => b.ExtendUser)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (bug == null)
            {
                return NotFound();
            }

            return View(bug);
        }

        // GET: Bugs/Create
        public IActionResult Create()
        {
            ViewData["ExtendUserId"] = new SelectList(_context.Users, "Id", "Id");
            return View();
        }

        // POST: Bugs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Description,IsDone,ExtendUserId")] Bug bug)
        {
            var user = _UserManager.Users.Where(u => u.Email == User.Identity.Name).ToList();
            bug.ExtendUserId = user[0].Id;
            bug.IsDone = false;
            if (ModelState.IsValid)
            {
                _context.Add(bug);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ExtendUserId"] = new SelectList(_context.Users, "Id", "Id", bug.ExtendUserId);
            return View(bug);
        }

        
        // GET: Bugs/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bug = await _context.Bug.FindAsync(id);
            if (bug == null)
            {
                return NotFound();
            }
            ViewData["ExtendUserId"] = new SelectList(_context.Users, "Id", "Id", bug.ExtendUserId);
            return View(bug);
        }

        // POST: Bugs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("Id,Title,Description,IsDone,ExtendUserId")] Bug bug)
        {
            if (id != bug.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(bug);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BugExists(bug.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ExtendUserId"] = new SelectList(_context.Users, "Id", "Id", bug.ExtendUserId);
            return View(bug);
        }

        // POST: Bugs/ChangeDone/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ChangeDone(long id, [Bind("Id,Title,Description,IsDone,ExtendUserId")] Bug bug)
        {
            if (id != bug.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(bug);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BugExists(bug.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ExtendUserId"] = new SelectList(_context.Users, "Id", "Id", bug.ExtendUserId);
            return View(bug);
        }

        // GET: Bugs/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bug = await _context.Bug
                .Include(b => b.ExtendUser)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (bug == null)
            {
                return NotFound();
            }

            return View(bug);
        }

        // POST: Bugs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var bug = await _context.Bug.FindAsync(id);
            _context.Bug.Remove(bug);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BugExists(long id)
        {
            return _context.Bug.Any(e => e.Id == id);
        }

        //most reporter User
        [HttpGet]
        public IEnumerable CountIsDone()
        {
            var CountIsDone = (from b in _context.Bug
                               group b by b.IsDone into bd
                               select new { Value = bd.Count(), Name = ( bd.Key == true ? "Done" : "Pending" ) }).ToList();
            return CountIsDone;
        }
    }
}

EveryBook/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EveryBook.Models;
using Microsoft.AspNetCore.Http;
using EveryBook.Data;
using System.Runtime.Serialization.Formatters.Binary;
using System.IO;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace EveryBook.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        private readonly EveryBookContext _context;
        public CartController(EveryBookContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            List<Book> cart;
            if (HttpContext.Session.Get(GetUniqueSessionKey("BooksInCart")) == null)
            {
                cart = new List<Book>();
                HttpContext.Session.SetString(GetUniqueSessionKey("BooksInCart"), JsonConvert.SerializeObject(cart));
                HttpContext.Session.SetInt32(GetUniqueSessionKey("NumOfBooksInCart"), 0);
                HttpContext.Session.SetInt32(GetUniqueSessionKey("TotalToPay"), 0);
            }
            else
            {
                cart = JsonConvert.DeserializeObject<List<Book>>(HttpContext.Session.GetString(GetUniqueSessionKey("BooksInCart")));
            }
            ViewData["DistributionUnitId"] = new SelectList(_context.DistributionUnit, "Id", "Name");
            return View(cart.ToList());
        }

        [HttpPost]
        public ActionResult AddToCart(int id)
        {
            List<Book> cart;
            Book bookToAdd = _context.Book.Where(b => b.Id == id).FirstOrDefault();
            if ((HttpContext.Session.Get(GetUniqueSessionKey("BooksInCart")) == null) || (JsonConvert.DeserializeObject<List<Book>>(HttpContext.Session.GetString(GetUniqueSessionKey("BooksInCart"))) == null))
            {
                cart = new List<Book>();
                HttpContext.Session.SetString(GetUniqueSessionKey("BooksInCart"), JsonConvert.SerializeObject(cart));
            }
            else
            {
                cart = JsonConvert.DeserializeObject<List<Book>>(HttpContext.Session.GetString(GetUniqueSessionKey("BooksInCart")));
            }

            if (isBookAlreadyInCart(id) == -1)
            {
                cart.Add(bookToAdd);
            }

            HttpContext.Session.SetString(GetUniqueSessionKey("BooksInCart"), JsonConvert.SerializeObject(cart));
            UpdateNumOfBooksInCart(true);
            UpdateTotalToPay(true, bookToAdd.Price);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult RemoveFromCart(int id)
        {
            List<Book> cart = JsonConvert.DeserializeObject<List<Book>>(HttpContext.Session.GetString(GetUniqueSessionKey("BooksInCart")));
            Book bookToRemove = _context.Book.Where(b => b.Id == id).FirstOrDefault();
            if (isBookAlreadyInCart(id) != -1)
            {
                UpdateNumOfBooksInCart(false);
                UpdateTotalToPay(false, bookToRemove.Price);
                cart.RemoveAt(isBookAlreadyInCart(id));

                HttpContext.Session.SetString(GetUniqueSessionKey("BooksInCart"), JsonConvert.SerializeObject(cart));
            }
            return RedirectToAction("Index");
        }

        private void UpdateNumOfBooksInCart(bool isAddAction)
        {
            if (HttpContext.Session.Get(GetUniqueSessionKey("NumOfBooksInCart")) == null)
            {
                HttpContext.Session.SetInt32(GetUniqueSessionKey("NumOfCartItems"), 1);
            }
            else
            {
                var NumOfBooksInCart = (int)HttpContext.Session.GetInt32(GetUniqueSessionKey("NumOfBooksInCart"));
                if(isAddAction)
                {
                    NumOfBooksInCart++;
                }
                else
                {
                    NumOfBooksInCart--;
                }
                HttpContext.Session.SetInt32(GetUniqueSessionKey("NumOfBooksInCart"), NumOfBooksInCart);
            }
        }

        private void UpdateTotalToPay(bool isAddAction, int bookPrice)
        {
            if (HttpContext.Session.Get(GetUniqueSessionKey("TotalToPay")) == null)
            {
                HttpContext.Session.SetInt32(GetUniqueSessionKey("TotalToPay"), bookPrice);
            }
            else
            {
                int TotalToPay = (int)HttpContext.Session.GetInt32(GetUniqueSessionKey("TotalToPay"));
                if (isAddAction)
                {
                    TotalToPay += bookPrice;
                }
                else
                {
                    TotalToPay -= bookPrice;
                }
                HttpContext.Session.SetInt32(GetUniqueSessionKey("TotalToPay"), TotalToPay);
            }
        }

        private string GetUniqueSessionKey(string key)
        {
            return HttpContext.User.Identity.Name.ToString() + key;
        }

        private int isBookAlreadyInCart(int id)
        {
            List<Book> cart = JsonConvert.DeserializeObject<List<Book>>(HttpContext.Session.GetString(GetUniqueSessionKey("BooksInCart")));
            if (cart != null)
            {
                for (int i = 0; i < cart.Count; i++)
                {
                    if (cart[i].Id == id)
                    {
                        return i;
                    }
                }
            }
            return -1;
        }
    }
}

EveryBook/Controllers/GenresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EveryBook.Data;
using EveryBook.Models;

namespace EveryBook.Controllers
{
    public class GenresController : Controller
    {
        private readonly EveryBookContext _context;

        public GenresController(EveryBookContext context)
        {
            _context = context;
        }

        // GET: Genres
        public async Task<IActionResult> Index([FromQuery] string? genreName)
        {
            IEnumerable<Genre> everyBookContext = _context.Genre;

            if (!String.IsNullOrEmpty(genreName))
            {
                everyBookContext = everyBookContext.Where(g => g.Name.ToLower().Contains(genreName.ToLower())).ToList();
            }

            return View(everyBookContext);
        }

        // GET: Genres/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var genre = await _context.Genre
                .FirstOrDefaultAsync(m => m.Id == id);
            if (genre == null)
            {
                return NotFound();
            }

            return View(genre);
        }

        // GET: Genres/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Genres/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,IsDeleted")] Genre genre)
        {
            if (ModelState.IsValid)
            {
                var isalreadyCreated = _context.Genre.Where(g => g.Name.ToLower() == genre.Name.ToLower()).FirstOrDefault();
                if (isalreadyCreated != null)
                {
                    if (isalreadyCreated.IsDeleted == false)
                    {
                        return View(genre);
                    }
                    isalreadyCreated.IsDeleted = false;
                    _context.Update(isalreadyCreated);
                } else
                {
                    _context.Add(genre);
                }
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(genre);
        }

        // GET: Genres/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var genre = await _context.Genre.FindAsync(id);
            if (genre == null)
            {
                return NotFound();
            }
            return View(genre);
        }

        // POST: Genres/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("Id,Name,IsDeleted")] Genre genre)
        {
            if (id != genre.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(genre);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GenreExists(genre.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(genre);
        }

        // GET: Genres/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var genre = await _context.Genre
                .FirstOrDefaultAsync(m => m.Id == id);
            if (genre == null)
            {
                return NotFound();
            }

            return View(genre);
        }

        // POST: Genres/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var genre = await _context.Genre.FindAsync(id);
            genre.IsDeleted = true;
            var books = _context.Book.Where(b => b.GenreId == id).ToArray();
            for (int i = 0; i < books.Length; i++)
            {
                books[i].IsDeleted = true;
                _context.Book.Update(books[i]);
            }
            _context.Genre.Update(genre);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GenreExists(long id)
        {
            return _context.Genre.Any(e => e.Id == id);
        }
    }
}

EveryBook/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<ExtendUser> SignInManager
@inject UserManager<ExtendUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EveryBook</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/everybook.png" width="50" height="50" /> EveryBook</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Books" asp-action="Index">Books</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Genres" asp-action="Index">Genres</a>
                        </li>
                        @if (SignInManager.IsSignedIn(User))
                        {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Orders" asp-action="Index">Orders</a>
                        </li>
                        @if (UserManager.IsInRoleAsync(UserManager.GetUserAsync(User).Result, "Admin").Result)
                            {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Bugs" asp-action="Index">Bugs</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Statistics">Statistics</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="UsersList">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DistributionUnits" asp-action="Index">Distribution-Units</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Locations" asp-action="Index">Locations</a>
                        </li>
                            }
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                    <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="Index">
                        <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-cart" viewBox="0 0 16 16" style="margin-left: 5px;">
                            <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l1.313 7h8.17l1.313-7H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
                        </svg>
                    </a>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - EveryBook - <a asp-area="" asp-controller="Home" asp-action="About">About</a> | <a asp-area="" asp-controller="Bugs" asp-action="Create">Report a bug</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>